apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giftcard-api
  namespace: giftcard-sentiment
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: giftcard-sentiment
      app.kubernetes.io/component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
